service: DynamoDB-apis

provider:
    name: aws
    runtime: nodejs20.x
    profile: typescript-node
    region: ap-south-1
    stage: dev

package:
    individually: true

functions:
    handler:
        handler: index.handler
        events:
          - http: ANY /{proxy+}
          - http: ANY /
            
   
   
                      